<a href="https://colab.research.google.com/github/Chaki34/python-basics/blob/main/%23%20PANDAS%20-%20working%20with%20Series%20data%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# PANDAS - working with Series data

import pandas as pd

data = pd.read_csv("https://raw.githubusercontent.com/logpresso/dataset/main/iris.csv")

data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [37]:
dataset = data['species'][

dataset

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
5    setosa
6    setosa
7    setosa
8    setosa
9    setosa
Name: species, dtype: object

In [17]:
series_data  = pd.Series(dataset)

type(series_data)

pandas.core.series.Series

In [23]:
len(series_data)

150

In [38]:
series_data.value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [29]:
type(series_data.value_counts())

pandas.core.series.Series

In [39]:
series_data[0:10]

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
5    setosa
6    setosa
7    setosa
8    setosa
9    setosa
Name: species, dtype: object

In [40]:
# task put my own index

# genrate own idx
idx = []

for i in range(10):
    idx.append(chr(97 + i))

print(idx)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [50]:
data3 = pd.Series(list(dataset), index=idx)

In [51]:
data3['a']

'setosa'

In [57]:
 new_data  = pd.concat([dataset, data3])

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
5    setosa
6    setosa
7    setosa
8    setosa
9    setosa
a    setosa
b    setosa
c    setosa
d    setosa
e    setosa
f    setosa
g    setosa
h    setosa
i    setosa
j    setosa
a    setosa
b    setosa
c    setosa
d    setosa
e    setosa
f    setosa
g    setosa
h    setosa
i    setosa
j    setosa
dtype: object

In [59]:
dataset = pd.Series([1, 2, 3])
data3 = pd.Series([4, 5])

new_data = pd.concat([dataset, data3])
new_data = new_data * 2

print(new_data)

0     2
1     4
2     6
0     8
1    10
dtype: int64