<a href="https://colab.research.google.com/github/Chaki34/python-basics/blob/main/PANDAS%20-%20Working%20with%20csv%20and%20html%20tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
# pandas - Working with excel

# pandas
import pandas  as pd

In [86]:
df = pd.read_excel("sample_data/pandas_practice_dataset.xlsx")
df.head()

,student_id,full_name,gender,date_of_birth,age,department,course,year,semester,city,...,coding_hours_week,monthly_expense,fees_paid,fees_due,placement_status,email,phone,is_active,total_score,grade
0,STU1001,Ishaan Paul,Male,2001-06-10,25,CSE,B.Tech,2,4,Mumbai,...,8.9,2277.0,90353,35369.0,Placed,student1@example.com,9.825545e+09,True,78.69,B
1,STU1002,Deb Kumar,Female,2007-03-31,19,IT,B.Tech,3,2,Delhi,...,15.0,3260.0,83169,6829.0,Not Eligible,student2@example.com,9.656987e+09,True,74.57,B
2,STU1003,Neha Dutta,Male,2002-03-30,24,CSE,B.Tech,3,6,Pune,...,8.6,6436.0,74634,16634.0,Placed,student3@example.com,9.162542e+09,True,62.88,C
3,STU1004,Deb Sen,Female,2001-03-12,25,CE,B.Tech,2,1,Howrah,...,4.0,4460.0,32802,0.0,Not Eligible,student4@example.com,9.813656e+09,True,62.76,C
4,STU1005,Zoya Mitra,Other,2007-07-19,19,IT,B.Tech,3,3,Delhi,...,7.0,5682.0,97570,11618.0,Higher Studies,student5@example.com,9.997495e+09,True,76.37,B

In [87]:
df.tail(30)

,student_id,full_name,gender,date_of_birth,age,department,course,year,semester,city,...,coding_hours_week,monthly_expense,fees_paid,fees_due,placement_status,email,phone,is_active,total_score,grade
225,STU1226,Zoya Ghosh,Male,2005-11-25,20,CSE,B.Tech,2,7,Durgapur,...,8.9,6373.0,73752,11113.0,Eligible,student226@example.com,9.424012e+09,True,54.13,D
226,STU1227,Nikhil Sharma,Female,2007-10-25,18,BBA,M.Tech,4,4,Chennai,...,13.0,7824.0,67353,13500.0,Not Eligible,student227@example.com,9.778338e+09,True,77.42,B
227,STU1228,Zoya Sharma,Male,2005-05-16,21,CSE,B.Tech,3,4,Delhi,...,4.5,5902.0,65392,5340.0,Not Eligible,student228@example.com,9.729678e+09,True,85.86,A
228,STU1229,Riya Das,Male,2004-03-30,22,CSE,BBA,2,5,Mumbai,...,11.8,8356.0,106819,19754.0,Higher Studies,student229@example.com,9.785762e+09,True,70.36,B
229,STU1230,Moumita Gupta,Female,1999-06-08,27,IT,BCA,4,4,Delhi,...,13.3,4240.0,76123,0.0,Not Eligible,student230@example.com,NaN,True,48.41,E
230,STU1231,Yash Dutta,Male,2004-07-21,22,CSE,MCA,4,4,Mumbai,...,7.5,9309.0,103987,19841.0,Placed,student231@example.com,9.272156e+09,False,80.05,A
231,STU1232,Pooja Sharma,Male,2006-07-15,20,MCA,MCA,2,4,Bengaluru,...,10.1,6841.0,81636,5739.0,Higher Studies,student232@example.com,9.599465e+09,True,64.06,C
232,STU1233,Rohan Sen,Male,2005-02-06,21,BBA,B.Tech,3,6,Pune,...,9.9,10827.0,72828,8995.0,Not Eligible,student233@example.com,9.235348e+09,True,76.61,B
233,STU1234,Arjun Chakraborty,Male,2003-05-23,23,CE,B.Tech,3,7,Delhi,...,3.9,13260.0,65301,20262.0,Not Eligible,student234@example.com,9.292675e+09,True,63.58,C
234,STU1235,Nikhil Gupta,Male,2001-01-06,25,EEE,B.Tech,2,2,Chennai,...,10.7,5183.0,74413,15945.0,Placed,student235@example.com,9.622291e+09,False,57.66,D
235,STU1236,Shreya Banerjee,Male,2002-10-20,23,CSE,BCA,2,7,Mumbai,...,16.1,5299.0,110528,27647.0,Higher Studies,student236@example.com,9.626335e+09,True,46.38,E
236,STU1237,Tanya Singh,Female,2003-01-11,23,ECE,B.Tech,2,5,Siliguri,...,8.1,5811.0,65484,3366.0,Higher Studies,student237@example.com,9.671596e+09,False,82.45,A
237,STU1238,Aniket Banerjee,Male,2006-08-11,20,EEE,B.Tech,3,4,Hyderabad,...,0.7,8168.0,123101,NaN,Eligible,student238@example.com,9.353050e+09,True,74.95,B
238,STU1239,Riya Mehta,Male,2005-10-12,20,ECE,BCA,2,7,Siliguri,...,4.6,10213.0,69869,25665.0,Placed,student239@example.com,9.740053e+09,True,86.70,A
239,STU1240,Moumita Singh,Female,2004-04-15,22,IT,BCA,4,6,Kolkata,...,0.0,4672.0,98499,19334.0,Not Eligible,student240@example.com,9.609921e+09,True,70.64,B
240,STU1241,Moumita Paul,Male,2003-09-26,23,ECE,BBA,3,8,Pune,...,14.5,7567.0,82385,20107.0,Higher Studies,student241@example.com,9.631475e+09,True,67.51,C
241,STU1242,Arjun Bose,Female,2001-02-18,25,ECE,BCA,1,5,Pune,...,11.8,6119.0,79230,28297.0,Higher Studies,student242@example.com,9.184746e+09,True,76.76,B
242,STU1243,Rohan Gupta,Female,2004-03-11,22,MCA,M.Tech,3,3,Siliguri,...,5.5,8231.0,62114,10125.0,Not Eligible,student243@example.com,9.675633e+09,True,60.20,C
243,STU1244,Tanmay Sen,Male,2004-04-05,22,BBA,B.Tech,2,7,Durgapur,...,0.9,10726.0,83229,7598.0,Not Eligible,student244@example.com,9.361715e+09,False,64.82,C
244,STU1245,Ananya Sharma,Female,2000-12-15,25,ECE,B.Tech,3,3,Bengaluru,...,3.8,5827.0,64151,21911.0,Not Eligible,student245@example.com,9.597186e+09,True,75.04,B
245,STU1246,Moumita Banerjee,Male,2004-07-25,22,EEE,B.Tech,3,4,Delhi,...,4.8,1824.0,54732,13207.0,Not Eligible,student246@example.com,9.745777e+09,True,65.79,C
246,STU1247,Varun Saha,Male,1998-04-17,28,CE,B.Tech,1,6,Chennai,...,8.5,8583.0,87153,28466.0,Placed,student247@example.com,9.504525e+09,True,51.84,D
247,STU1248,Tanya Banerjee,Male,2005-11-18,20,CSE,BBA,2,6,Pune,...,8.4,4168.0,73562,19437.0,Eligible,student248@example.com,9.946765e+09,True,79.87,A
248,STU1249,Ananya Das,Male,1998-02-17,28,BBA,B.Tech,1,7,Siliguri,...,14.7,6099.0,115318,7520.0,Not Eligible,student249@example.com,9.698299e+09,True,65.40,C
249,STU1250,Sneha Saha,Female,2007-12-24,18,BBA,BBA,1,5,Siliguri,...,4.5,8704.0,103000,19061.0,Not Eligible,student250@example.com,9.772002e+09,True,35.29,F
250,STU1149,Neha Mehta,Male,2003-10-24,22,EEE,B.Tech,2,4,Hyderabad,...,1.0,5423.0,88913,18147.0,Not Eligible,student149@example.com,9.894110e+09,True,56.03,D
251,STU1220,Sneha Gupta,Male,2000-10-25,25,BBA,B.Tech,3,4,Siliguri,...,11.8,4882.0,63063,20347.0,Placed,student220@example.com,9.312419e+09,True,64.95,C
252,STU1095,Abhishek Ghosh,Male,2002-07-27,24,CSE,B.Tech,3,7,Delhi,...,4.1,6492.0,105092,16803.0,Placed,student95@example.com,9.102337e+09,True,63.55,C
253,STU1085,Moumita Roy,Female,2003-11-23,22,ME,B.Tech,1,6,Bengaluru,...,18.5,7929.0,129729,28103.0,Placed,student85@example.com,9.939644e+09,True,65.90,C
254,STU1004,Deb Sen,Female,2001-03-12,25,CE,B.Tech,2,1,Howrah,...,4.0,4460.0,32802,0.0,Not Eligible,student4@example.com,9.813656e+09,True,62.76,C

In [88]:
type(df)

pandas.core.frame.DataFrame

In [89]:
df.columns

Index(['student_id', 'full_name', 'gender', 'date_of_birth', 'age',
       'department', 'course', 'year', 'semester', 'city', 'hostel',
       'admission_mode', 'admission_date', 'scholarship_type', 'blood_group',
       'attendance_pct', 'assignment_score', 'midterm_score', 'final_score',
       'projects_completed', 'coding_hours_week', 'monthly_expense',
       'fees_paid', 'fees_due', 'placement_status', 'email', 'phone',
       'is_active', 'total_score', 'grade'],
      dtype='object')

In [90]:
df[['full_name','age']]

          full_name  age
0       Ishaan Paul   25
1         Deb Kumar   19
2        Neha Dutta   24
3           Deb Sen   25
4        Zoya Mitra   19
..              ...  ...
250      Neha Mehta   22
251     Sneha Gupta   25
252  Abhishek Ghosh   24
253     Moumita Roy   22
254         Deb Sen   25

[255 rows x 2 columns]

In [91]:
print(df["full_name"].to_string())

0              Ishaan Paul
1                Deb Kumar
2               Neha Dutta
3                  Deb Sen
4               Zoya Mitra
5          Varun Mukherjee
6          Neha Chatterjee
7        Kavya Chakraborty
8                Tanya Das
9               Vivek Bose
10             Moumita Roy
11            Aditi Sharma
12             Nikhil Bose
13              Yash Mehta
14           Abhishek Saha
15            Aniket Gupta
16              Riya Kumar
17           Moumita Mitra
18             Nikhil Paul
19        Yash Chakraborty
20             Arjun Mitra
21            Ishaan Ghosh
22            Ishaan Verma
23            Ananya Singh
24             Sayan Ghosh
25                Zoya Das
26             Sneha Kumar
27              Aniket Sen
28            Nikhil Dutta
29        Riya Chakraborty
30             Rahul Mehta
31            Ananya Verma
32        Kavya Chatterjee
33               Aditi Roy
34              Tanya Saha
35            Ananya Verma
36               Zoya Bose
37              Aditi Saha
38      Moumita Chatterjee
39             Rahul Gupta
40              Riya Dutta
41             Rahul Dutta
42            Tanmay Gupta
43             Pooja Verma
44              Riya Patel
45           Krishna Kumar
46            Pooja Sharma
47                Yash Sen
48          Krishna Sharma
49            Nikhil Dutta
50         Vivek Mukherjee
51            Shreya Mehta
52       Kavya Chakraborty
53           Aditya Sharma
54       Abhishek Banerjee
55               Meera Sen
56              Zoya Ghosh
57              Aniket Sen
58           Krishna Dutta
59              Nikhil Das
60             Aarav Gupta
61          Varun Banerjee
62             Aditya Bose
63       Kavya Chakraborty
64       Aarav Chakraborty
65             Arjun Kumar
66       Rahul Chakraborty
67          Aarav Banerjee
68              Zoya Singh
69            Ishaan Ghosh
70              Riya Kumar
71               Zoya Saha
72            Aniket Patel
73              Shreya Sen
74             Sakshi Paul
75          Deb Chatterjee
76        Moumita Banerjee
77               Varun Sen
78             Pooja Kumar
79         Neha Chatterjee
80               Pooja Sen
81          Abhishek Mitra
82               Tanya Das
83             Meera Patel
84             Moumita Roy
85             Aniket Bose
86             Nikhil Paul
87       Moumita Mukherjee
88                Zoya Sen
89          Moumita Sharma
90              Aarav Paul
91             Pooja Ghosh
92              Aditya Sen
93              Diya Dutta
94          Abhishek Ghosh
95        Moumita Banerjee
96             Aarav Mitra
97              Meera Bose
98             Vivek Kumar
99          Abhishek Ghosh
100            Sneha Mehta
101          Moumita Mehta
102              Zoya Paul
103             Nikhil Sen
104      Aditi Chakraborty
105        Sakshi Banerjee
106           Sakshi Mehta
107         Abhishek Mehta
108              Aditi Das
109        Aniket Banerjee
110           Aarav Sharma
111             Shreya Das
112            Tanmay Bose
113               Zoya Roy
114       Varun Chatterjee
115        Varun Mukherjee
116            Vivek Mehta
117          Diya Banerjee
118              Sneha Das
119         Diya Mukherjee
120            Rohan Gupta
121            Aarav Ghosh
122             Aniket Roy
123      Rohan Chakraborty
124       Sneha Chatterjee
125     Shreya Chakraborty
126            Shreya Paul
127            Ishaan Paul
128         Krishna Sharma
129              Kavya Sen
130            Sayan Dutta
131        Aarav Mukherjee
132           Aniket Verma
133             Varun Saha
134             Aditya Sen
135           Aniket Gupta
136             Zoya Gupta
137              Yash Paul
138           Aniket Mehta
139           Aditi Sharma
140             Rohan Bose
141         Arjun Banerjee
142         Abhishek Ghosh
143    Krishna Chakraborty
144           Shreya Gupta
145      Rohan Chakraborty
146           Sneha Sharma
147             Vivek Paul
148             Neha Mehta
149       Kavya Chatterjee
150             Diya Dutta
151      Sneha Chakraborty
152      Rohan Chakraborty
153             Yash Verma
154            Rahul Verma
155      Aditi Chakraborty
156            Rohan Ghosh
157          Ananya Sharma
158          Ananya Sharma
159            Rahul Gupta
160            Sneha Dutta
161     Ishaan Chakraborty
162          Sakshi Sharma
163             Rohan Bose
164         Abhishek Mitra
165            Tanya Singh
166            Moumita Roy
167             Diya Patel
168           Shreya Dutta
169           Abhishek Das
170          Tanmay Sharma
171           Aniket Kumar
172         Aarav Banerjee
173           Aniket Gupta
174      Shreya Chatterjee
175           Aditya Mehta
176            Sakshi Bose
177           Aniket Singh
178             Tanmay Roy
179           Aditya Ghosh
180            Arjun Mehta
181      Rahul Chakraborty
182          Aniket Sharma
183           Sneha Sharma
184           Aditya Verma
185              Yash Saha
186      Tanya Chakraborty
187            Kavya Singh
188            Vivek Verma
189               Riya Das
190          Abhishek Saha
191            Aditi Mehta
192           Kavya Sharma
193      Krishna Mukherjee
194            Tanya Gupta
195            Ishaan Saha
196      Varun Chakraborty
197            Sayan Patel
198             Aniket Sen
199        Yash Chatterjee
200             Pooja Paul
201            Aarav Dutta
202            Rahul Gupta
203             Rahul Bose
204           Shreya Kumar
205             Aniket Das
206            Aditi Mitra
207             Yash Mehta
208             Sneha Saha
209             Diya Kumar
210        Tanya Mukherjee
211        Aniket Banerjee
212            Aarav Dutta
213            Tanmay Bose
214        Nikhil Banerjee
215      Ishaan Chatterjee
216             Diya Patel
217            Sneha Kumar
218           Aditya Dutta
219            Sneha Gupta
220            Pooja Verma
221            Aniket Saha
222          Moumita Mitra
223           Sakshi Mitra
224        Aniket Banerjee
225             Zoya Ghosh
226          Nikhil Sharma
227            Zoya Sharma
228               Riya Das
229          Moumita Gupta
230             Yash Dutta
231           Pooja Sharma
232              Rohan Sen
233      Arjun Chakraborty
234           Nikhil Gupta
235        Shreya Banerjee
236            Tanya Singh
237        Aniket Banerjee
238             Riya Mehta
239          Moumita Singh
240           Moumita Paul
241             Arjun Bose
242            Rohan Gupta
243             Tanmay Sen
244          Ananya Sharma
245       Moumita Banerjee
246             Varun Saha
247         Tanya Banerjee
248             Ananya Das
249             Sneha Saha
250             Neha Mehta
251            Sneha Gupta
252         Abhishek Ghosh
253            Moumita Roy
254                Deb Sen

In [92]:
type(df["full_name"])

pandas.core.series.Series

In [93]:
df[["full_name","age"]] # list of series item
print(df[["full_name","age"]]) # list of series item
type(df[["full_name","age"]] )

          full_name  age
0       Ishaan Paul   25
1         Deb Kumar   19
2        Neha Dutta   24
3           Deb Sen   25
4        Zoya Mitra   19
..              ...  ...
250      Neha Mehta   22
251     Sneha Gupta   25
252  Abhishek Ghosh   24
253     Moumita Roy   22
254         Deb Sen   25

[255 rows x 2 columns]

pandas.core.frame.DataFrame

In [94]:
# know datatypes of column
df.dtypes

student_id                    object
full_name                     object
gender                        object
date_of_birth         datetime64[ns]
age                            int64
department                    object
course                        object
year                           int64
semester                       int64
city                          object
hostel                        object
admission_mode                object
admission_date        datetime64[ns]
scholarship_type              object
blood_group                   object
attendance_pct               float64
assignment_score             float64
midterm_score                float64
final_score                  float64
projects_completed             int64
coding_hours_week            float64
monthly_expense              float64
fees_paid                      int64
fees_due                     float64
placement_status              object
email                         object
phone                        float64
is_active                       bool
total_score                  float64
grade                         object
dtype: object

In [95]:
!pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (6.1.3)

In [96]:
# External soruce read  -



store = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2023_totals.html")

In [97]:
type(pd.read_html("https://www.basketball-reference.com/leagues/NBA_2023_totals.html"))

list

In [98]:
# how much table avl

len(pd.read_html("https://www.basketball-reference.com/leagues/NBA_2023_totals.html"))

2

In [99]:
data0 = store[0] # fetch the first table

In [100]:
# fetch second table
data1= store[1]

In [101]:
data0.head(10)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,Jayson Tatum,24.0,BOS,SF,74.0,74.0,2732.0,727.0,1559.0,...,571.0,649.0,342.0,78.0,51.0,213.0,160.0,2225.0,1.0,"MVP-4,CPOY-10,AS,NBA1"
1,2.0,Joel Embiid,28.0,PHI,C,66.0,66.0,2284.0,728.0,1328.0,...,557.0,670.0,274.0,66.0,112.0,226.0,205.0,2183.0,1.0,"MVP-1,DPOY-9,CPOY-5,AS,NBA1"
2,3.0,Luka Dončić,23.0,DAL,PG,66.0,66.0,2391.0,719.0,1449.0,...,515.0,569.0,529.0,90.0,33.0,236.0,166.0,2138.0,10.0,"MVP-8,CPOY-8,AS,NBA1"
3,4.0,Shai Gilgeous-Alexander,24.0,OKC,PG,68.0,68.0,2416.0,704.0,1381.0,...,270.0,329.0,371.0,112.0,65.0,192.0,192.0,2135.0,0.0,"MVP-5,CPOY-7,AS,NBA1"
4,5.0,Giannis Antetokounmpo,28.0,MIL,PF,63.0,63.0,2024.0,707.0,1278.0,...,605.0,742.0,359.0,52.0,51.0,246.0,197.0,1959.0,6.0,"MVP-3,DPOY-6,AS,NBA1"
5,6.0,Anthony Edwards,21.0,MIN,SG,79.0,79.0,2842.0,707.0,1541.0,...,411.0,458.0,350.0,125.0,58.0,259.0,186.0,1946.0,0.0,AS
6,7.0,Julius Randle,28.0,NYK,PF,77.0,77.0,2737.0,658.0,1432.0,...,626.0,767.0,316.0,49.0,21.0,216.0,233.0,1936.0,0.0,"CPOY-14,AS,NBA3"
7,8.0,Donovan Mitchell,26.0,CLE,SG,68.0,68.0,2432.0,679.0,1402.0,...,226.0,289.0,301.0,99.0,27.0,180.0,168.0,1922.0,0.0,"MVP-6,CPOY-6,AS,NBA2"
8,9.0,Trae Young,24.0,ATL,PG,73.0,73.0,2541.0,597.0,1390.0,...,161.0,217.0,741.0,80.0,9.0,300.0,104.0,1914.0,0.0,NaN
9,10.0,Zach LaVine,27.0,CHI,SG,77.0,77.0,2768.0,673.0,1388.0,...,303.0,345.0,327.0,69.0,18.0,194.0,159.0,1913.0,0.0,NaN

In [102]:
data1.tail(20)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
198,199.0,Vlatko Čančar,25.0,DEN,PF,5.0,0.0,10.0,0.0,5.0,...,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
199,200.0,Amir Coffey,25.0,LAC,SF,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
200,201.0,Robert Covington,32.0,LAC,PF,2.0,0.0,12.0,0.0,3.0,...,2.0,2.0,2.0,0.0,1.0,0.0,2.0,0.0,0.0,NaN
201,202.0,Dewayne Dedmon,33.0,PHI,C,1.0,0.0,5.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,NaN
202,203.0,Kessler Edwards,22.0,SAC,SF,6.0,0.0,7.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
203,204.0,Blake Griffin,33.0,BOS,C,1.0,0.0,6.0,0.0,1.0,...,1.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,NaN
204,205.0,Montrezl Harrell,29.0,PHI,C,2.0,0.0,7.0,0.0,3.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
205,206.0,Udonis Haslem,42.0,MIA,C,2.0,0.0,3.0,0.0,3.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
206,207.0,Aaron Holiday,26.0,ATL,PG,1.0,0.0,4.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN
207,208.0,DaQuan Jeffries,25.0,NYK,SG,2.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,NaN
208,209.0,Meyers Leonard,30.0,MIL,C,2.0,0.0,5.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
209,210.0,Jordan McLaughlin,26.0,MIN,PG,2.0,0.0,14.0,0.0,4.0,...,2.0,2.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,NaN
210,211.0,Patty Mills,34.0,BRK,PG,1.0,0.0,5.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
211,212.0,Josh Minott,20.0,MIN,SF,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,NaN
212,213.0,Wendell Moore Jr.,21.0,MIN,SG,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN
213,214.0,Jason Preston,23.0,LAC,PG,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
214,215.0,Derrick Rose,34.0,NYK,PG,1.0,0.0,3.0,0.0,4.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
215,216.0,Ricky Rubio,32.0,CLE,PG,3.0,0.0,17.0,0.0,1.0,...,4.0,6.0,3.0,1.0,0.0,5.0,5.0,0.0,0.0,NaN
216,217.0,Edmond Sumner,27.0,BRK,SG,1.0,0.0,4.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
217,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
data0.columns

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Trp-Dbl', 'Awards'],
      dtype='object')

In [104]:
data0.dtypes

Rk         float64
Player      object
Age        float64
Team        object
Pos         object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Trp-Dbl    float64
Awards      object
dtype: object

In [105]:
data0[['2PA', '2P%', 'eFG%', 'FT', 'FTA',]]

        2PA    2P%   eFG%     FT    FTA
0     873.0  0.558  0.543  531.0  622.0
1    1128.0  0.587  0.573  661.0  771.0
2     908.0  0.588  0.560  515.0  694.0
3    1213.0  0.533  0.531  669.0  739.0
4    1107.0  0.596  0.572  498.0  772.0
..      ...    ...    ...    ...    ...
675     1.0  0.000  0.000    0.0    0.0
676     0.0    NaN    NaN    0.0    0.0
677     2.0  0.000  0.000    0.0    0.0
678     0.0    NaN    NaN    0.0    0.0
679     NaN  0.548  0.545    NaN    NaN

[680 rows x 5 columns]

In [106]:
# copy data and store it

data0.to_csv("Stas.csv",index=False) # use false sothat not show any extra indexing

In [107]:
# to store in excel

data1.to_excel("Stas.xlsx")